sudo: required
services:
  - docker

before_install:
  - docker build -t thainam83vn/bi4a-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run thainam83vn/bi4a-client-test npm test -- --coverage

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t thainam83vn/bi4a-client ./client
  - docker build -t thainam83vn/bi4a-nginx ./nginx
  - docker push thainam83vn/bi4a-client
  - docker push thainam83vn/bi4a-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: eazybi-app
  env: EazybiApp-env
  bucket_name: elasticbeanstalk-us-east-1-793085127332
  bucket_path: app2
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
